### ISSUE TITLE
Tests fail to build on boost 1.76

### ISSUE THREAD

**Issue by vinipsmaker** [breese/trial.protocol#51]
```
include/trial/protocol/detail/lightweight_test.hpp:42:28: error: no member named 'report_errors_remind' in namespace 'boost::detail'
            boost::detail::report_errors_remind();
```

**Comment by breese** [comment]
Already fixed on `develop`. I guess it is time to merge to `master`

**Comment by vinipsmaker** [comment]
Oops, I was looking at the wrong branch.

Okay, I'm having a different error on branch `develop` (this time on Boost 1.76):

```
/home/vinipsmaker/Projetos/trial.protocol/test/dynamic/std/partial_sum_suite.cpp:194:5: error: too few arguments to function call, expected 5, have 4
    TRIAL_PROTOCOL_TEST_THROW_EQUAL(op(),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/vinipsmaker/Projetos/trial.protocol/cmake/../include/trial/protocol/core/detail/lightweight_test.hpp:235:66: note: expanded from macro 'TRIAL_PROTOCOL_TEST_THROW_EQUAL'
              (#EXCEP, __FILE__, __LINE__, BOOST_CURRENT_FUNCTION);     \
                                                                 ^
/usr/include/boost/core/lightweight_test.hpp:125:13: note: 'throw_failed_impl' declared here
inline void throw_failed_impl(const char* expr, char const * excep, char const * file, int line, char const * function)
            ^
```

**Comment by breese** [comment]
Possibly fixed in 38989dd3b2138d3a21d59b8140ec20c9ccd88c57

**Comment by vinipsmaker** [comment]
Yes, it fixed. Thanks.

I'm having troubles on other test now.

```
/home/vinipsmaker/Projetos/trial.protocol/test/dynamic/variable_comparison_suite.cpp:490:33: error: no member named 'numeric_limits' in namespace 'std'
        const variable big(std::numeric_limits<signed int>::max());
                           ~~~~~^
```

Hopefully just a missing include.

I'm using clang 12.0.0.

**Comment by breese** [comment]
Yes it was: ba3e9898b625da90c40fe92c77575370f4e12d3b

**Comment by vinipsmaker** [comment]
Okay. I can compile and run the tests again. Thanks.
